apiVersion: v1
kind: Service
metadata:
  name: {{ include "kierroskone.fullname" . }}
  namespace: {{ include "kierroskone.namespace" }}
  labels:
    {{- include "kierroskone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kierroskone.selectorLabels" . | nindent 4 }}
